### PR TITLE
Make `activate` method awaitable

### PR DESCRIPTION
**Pull request by bambinoua**
Minor fix which allows to `start` asynchronously.

### CODE REVIEW

**Comment by KammererTob** [comment]
I am not seeing this in the effective dart documentation. Can you provide a link to that?
Other than that: What would be the use-case for returning a `Future` here? To me it implies that it might be useful to `await` those functions, which i am not so sure there is a value for.

**Comment by bambinoua** [comment]
> I am not seeing this in the effective dart documentation. Can you provide a link to that?

[do-use-futurevoid-as-the-return-type-of-asynchronous-members-that-do-not-produce-values](https://dart.dev/guides/language/effective-dart/design#do-use-futurevoid-as-the-return-type-of-asynchronous-members-that-do-not-produce-values)

> Other than that: What would be the use-case for returning a `Future` here? To me it implies that > it might be useful to `await` those functions, which i am not so sure there is a value for.

This fix allows to use `await` keyword for calling `start` method which helps to ensure that connection is established after `start` call. For example, in my case I need few websockets but I need have a moment when _all of them_ are connected (not one by one). To do so now I implemented a wrapper (little boilerplate) with using `Completer` which completes in `onConnect` callback but why do I need this if just this simple fix solves the issue.

The sample code can be:

```dart
FutureBuilder(
  future: Future.wait([
    websocket1.start(),
    websocket2.start(),
    ...
  ]),
  builder: ...
)
```

**Comment by KammererTob** [comment]
Thanks for the clarifications. The link you provided also states:

> For asynchronous functions that do not return a useful value and where no callers need to await the asynchronous work or handle an asynchronous failure, use a return type of void.

In it's current form the only thing that could be awaited is the WebSocket connection, but *NOT* the Stomp protocol connection. At the moment the connect frame is send without waiting for the response. When the response comes in the callback is being called (https://github.com/blackhorse-one/stomp_dart_client/blob/900ec562c4cdcba8b596f7ff33198a6d645df20f/lib/stomp_handler.dart#L141)

I am not opposed to restructure the code at some point to make it completely awaitable, but in it's current form i don't see the benefit of returning a Future here.

**Comment by bambinoua** [comment]
> i don't see the benefit of returning a Future here.

Please look at my examples again. This is the benefit. And I repeat I need to create few (STOMP) websockets and I need to know the moment when all of them ready to accept subscriptions. The current functionality does not allow it.

Maybe in most cases it is enough to use callback `onConnect` but let's say returning Future is something like _sugar_. Moreover it does not involve too many efforts and don't break anything.

**Comment by KammererTob** [comment]
> Please look at my examples again. This is the benefit. And I repeat I need to create few (STOMP) websockets and I need to know the moment when all of them ready to accept subscriptions. The current functionality does not allow it.

I understand that, but the STOMP connection (ready to accept subscriptions) cannot be awaited at the moment because the transmission of the `CONNECT` frame is not async. It doesn't wait for the `CONNECTED` frame from the server here. So even if you return a `Future` here, it only signals that the *WebSocket* connection was established, but **not** the STOMP handshake

**Comment by bambinoua** [comment]
> it only signals that the WebSocket connection was established

That's right! To subscribe to topic we **must have an established websocket connection (not STOMP)**. If websocket is not connected then STOMP is useless because, you know, it works over WS. Again, no WS connection - no any STOMP frame.

**Absolutely non-working code**
```dart
final stompClient = StompClient(...);
stompClient.activate();
stompClient.subscribe(...) // <-- this will not work because at this moment WS is 
                           //     not yet connected, so any STOMP frames senseless.
```
so I need to implement something like this:

**Basically, working code**

```dart
StompClient stompClient;
stompClient = StompClient(
  onConnect: (frame) {
    stompClient.subscribe(...); // <-- WS (and, of course, STOMP) are connected
  }  
);
stompClient.activate();
```
But what about if need 2,3,5 websockets and know the moment when _all ones will be connected_?

**Nice code**

```dart
// This lines can be executed on upper level.
final stompClients = List.generate(3, (_) => StompClient(...));
final connections = Future.wait(stompClients.map((client) => client.activate()));
// At this moment all websockets and STOMP protocols connected.

// These lines can be used deeper.
stompClient[0].subscribe(...);
stompClient[1].subscribe(...);
```

**Comment by KammererTob** [comment]
> To subscribe to topic we must have an established websocket connection (not STOMP)
You need to have both. A established WebSocket connection and on that WebSocket a completed STOMP handshake. Any decently implemented STOMP server will reject subscribe frames if the initial connect handshake wasn't completed. And that is my point. In its current form the Future returned here will only be for the former, not the latter.

I am not saying that i don't see the value you laid out in your examples, but in it's current form it is not possible without some more rework.

**Comment by bambinoua** [comment]
> You need to have both.

Yes, both but STOMP will be sent right after WS connection establiched..

> but in it's current form it is not possible without some more rework.

More rework? All that does this PR is just update return value for 3 procedures and minor refactor of `_connect` method of `StompClient`

Let's see:
```dart
final stompClient = StompClient();
await stompClient.activate();
|
|--> await _connect();
     |
     |--> _handler = StompHandler();
          await _handler.start();
          |
          |-->  _channel = await platform.connect(config);
                _channel!.stream.listen(_onData, onError: _onError, onDone: _onDone);
                _connectToStomp();
                |
                |--> _transmit(command: 'CONNECT', headers: connectHeaders);
```
So what do we see? The CONNECT frame will be sent **after all awaited calls** and `transmit` methods will be executed **only after** `await platform.connect(config)` what I am talking about. 

All what is changed in your code is adding `Future<void>` instead `void` and change some methods call to async mode. What is the _more rework_?

**Comment by KammererTob** [comment]
Yes. The CONNECT frame is being send, but the code is currently **not** awaiting the response of the server in form of a CONNECTED frame. Only after that frame was received we can be sure that the STOMP connection was succesfully established and is able to handle subscriptions.

**Review by mohamed-yahyaoui — APPROVED** [review]
This PR should be accepted because when we subscribe after connection activation it throws an exception as it did not await the activation method

**Comment by KammererTob** [comment]
> This PR should be accepted because when we subscribe after connection activation it throws an exception as it did not await the activation method

You should handle subscriptions in the `onConnect` callback. This method is called when the connection is completely established.

**Pull request closed without merging**
