### PR TITLE
Make connectUrl lazy and once initialized

### PR DESCRIPTION
**Pull request by MacDeveloper1**
This PR fixes the issue #95

### CODE REVIEW

**Comment by KammererTob** [comment]
Thanks for the PR. Might it be possible to add some tests for that? Specifically that is always returns the same URL while conntected and that it regenerates the session_id/url on each connect? Just to prevent regressions in the future. Thanks!

**Comment by MacDeveloper1** [comment]
> Might it be possible to add some tests for that?

I've add the test and before update the dart SDK constraints because I was using `records` for test.

**Comment by KammererTob** [comment]
I would rather not tighten the constraints just for unit tests. Is it possible to rewrite them so that the old constraints can be kept? Sorry for the additional effort.

**Comment by MacDeveloper1** [comment]
Hi. I have strange thing.
I remove 2 last commits from remote where I changed constrains (one commit) and added a test (second commit) and then commit new modification (https://github.com/MacDeveloper1/stomp_dart_client/commit/a605ff130de7d6a55e362903c7cb796a38728574).

It is present in my repo but I didn't see it in this PR.

Don't you know what I need to do to add it to PR?

**Review by KammererTob — APPROVED** [review]

**Comment by KammererTob** [comment]
Thanks for the PR!

**Pull request merged**
